### PR TITLE
Bump eslint-plugin-import to v2.0.0 (#233)

### PR DESCRIPTION
**Pull request by zdoc01**
For #233. Did some preliminary testing in my local by overriding some of the `eslint-config-airbnb` dependency  definitions. Build seems to be passing with a few warnings.

We'll need to wait for airbnb to publish a new version with the updated `eslint-plugin-import` dependency before these changes can be merged. They've already [made the change on master](https://github.com/airbnb/javascript/commit/0bb3eb541203aee1b134bef06940557cf7a30007), so hopefully it's coming down the pipe soon. We'll probably need to bump the config version in `package.json` as well once that happens.

I'll be happy to check back in on this once the airbnb changes have been published.

### CODE REVIEW

**Comment by willdurand** [comment]
why did you change some regexps?

**Comment by zdoc01** [comment]
Hey @willdurand - if you check out [this failed build of master](https://circleci.com/gh/zdoc01/monod/1) you'll see that eslint is failing on those regular expressions:

```bash
/home/ubuntu/monod/app/components/Markdown/extra-keys.js
  14:42  error  Unnecessary escape character: \[  no-useless-escape
  14:46  error  Unnecessary escape character: \/  no-useless-escape

/home/ubuntu/monod/app/modules/documents.js
  144:43  error  Unnecessary escape character: \-  no-useless-escape
  144:53  error  Unnecessary escape character: \]  no-useless-escape
```

I made the changes to ensure the build wouldn't fail on that step.

**Comment by willdurand** [comment]
Ooops ok. Thanks @zdoc01. Could you update this PR maybe?

**Comment by zdoc01** [comment]
@willdurand - It doesn't look as though airbnb has published a new version of `eslint-config-airbnb` just yet. Was there something specific you wanted me to update? This branch still throws the following when executing `npm ls` due to the missing peer dependencies:

```bash
npm ERR! peer dep missing: eslint-plugin-import@^1.16.0, required by eslint-config-airbnb@12.0.0
npm ERR! peer dep missing: eslint-plugin-import@^1.16.0, required by eslint-config-airbnb-base@8.0.0
```

But that's still out of my control at this point.

**Comment by willdurand** [comment]
Ok, just wanted to be sure. So I suppose we cannot do anything right now...

**Comment by zdoc01** [comment]
@willdurand - Looks like a new version of eslint-config-airbnb was published last night! I bumped a few of the dependencies associated with this, as well as fixed the new eslint failures. It looks like they were all related to the [comma-dangle rule](http://eslint.org/docs/rules/comma-dangle).

Build is passing locally. The circleci build is failing with timeouts that appear to be unrelated to any of my changes (there are issues connecting to Sauce Labs). Let me know if you see any other issues and need me to make any additional changes.

**Comment by willdurand** [comment]
LGTM, thanks!

**Comment by willdurand** [comment]
Hum. This is weird. Circle gets the following output now:

```
npm install
npm WARN peerDependencies The peer dependency eslint@^3.9.1 included from eslint-config-airbnb will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency eslint-plugin-react@^6.6.0 included from eslint-config-airbnb will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN peerDependencies The peer dependency eslint@^3.9.1 included from eslint-config-airbnb-base will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
-
> monod@4.0.0 postinstall /home/ubuntu/monod
> npm run build


> monod@4.0.0 build /home/ubuntu/monod
> NODE_ENV=production webpack

clean-webpack-plugin: /home/ubuntu/monod/build has been removed.
Hash: 6e6134a07b11bde5c1f7
Version: webpack 1.13.1
Time: 1998ms
                     Asset      Size  Chunks             Chunk Names
               favicon.ico   15.1 kB          [emitted]  
                index.html   1.49 kB          [emitted]  
                     sw.js   4.22 kB          [emitted]  
appcache/manifest.appcache  88 bytes          [emitted]  
    appcache/manifest.html  58 bytes          [emitted]  
                robots.txt  22 bytes          [emitted]  
    + 1 hidden modules

ERROR in ./app/index.jsx
Module build failed: Error: /home/ubuntu/monod/node_modules/eslint-config-airbnb/node_modules/eslint-config-airbnb-base/rules/style.js:
	Configuration for rule "func-name-matching" is invalid:
	Value "always,[object Object]" has more items than allowed.
	Value "always" is the wrong type.

Referenced from: /home/ubuntu/monod/node_modules/eslint-config-airbnb/node_modules/eslint-config-airbnb-base/index.js
Referenced from: airbnb
Referenced from: /home/ubuntu/monod/.eslintrc
    at validateRuleOptions (/home/ubuntu/monod/node_modules/eslint/lib/config/config-validator.js:115:15)
    at /home/ubuntu/monod/node_modules/eslint/lib/config/config-validator.js:162:13
    at Array.forEach (native)
    at Object.validate (/home/ubuntu/monod/node_modules/eslint/lib/config/config-validator.js:161:35)
    at load (/home/ubuntu/monod/node_modules/eslint/lib/config/config-file.js:522:19)
    at /home/ubuntu/monod/node_modules/eslint/lib/config/config-file.js:391:36
    at Array.reduceRight (native)
    at applyExtends (/home/ubuntu/monod/node_modules/eslint/lib/config/config-file.js:362:28)
    at load (/home/ubuntu/monod/node_modules/eslint/lib/config/config-file.js:529:22)
    at /home/ubuntu/monod/node_modules/eslint/lib/config/config-file.js:391:36
    at Array.reduceRight (native)
    at applyExtends (/home/ubuntu/monod/node_modules/eslint/lib/config/config-file.js:362:28)
    at load (/home/ubuntu/monod/node_modules/eslint/lib/config/config-file.js:529:22)
    at /home/ubuntu/monod/node_modules/eslint/lib/config/config-file.js:391:36
    at Array.reduceRight (native)
    at applyExtends (/home/ubuntu/monod/node_modules/eslint/lib/config/config-file.js:362:28)
    at Object.load (/home/ubuntu/monod/node_modules/eslint/lib/config/config-file.js:529:22)
    at loadConfig (/home/ubuntu/monod/node_modules/eslint/lib/config.js:63:33)
    at getLocalConfig (/home/ubuntu/monod/node_modules/eslint/lib/config.js:130:29)
    at Config.getConfig (/home/ubuntu/monod/node_modules/eslint/lib/config.js:256:22)
    at processText (/home/ubuntu/monod/node_modules/eslint/lib/cli-engine.js:224:33)
    at CLIEngine.executeOnText (/home/ubuntu/monod/node_modules/eslint/lib/cli-engine.js:756:26)
    at lint (/home/ubuntu/monod/node_modules/eslint-loader/index.js:42:18)
    at Object.module.exports (/home/ubuntu/monod/node_modules/eslint-loader/index.js:166:3)
Child __offline_serviceworker:
        + 4 hidden modules
Child html-webpack-plugin for "index.html":
        + 3 hidden modules
npm ERR! Linux 3.13.0-100-generic
npm ERR! argv "/home/ubuntu/nvm/versions/node/v5.1.0/bin/node" "/home/ubuntu/nvm/versions/node/v5.1.0/bin/npm" "install"
npm ERR! node v5.1.0
npm ERR! npm  v2.13.5
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package eslint-plugin-react@6.4.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer eslint-config-airbnb@13.0.0 wants eslint-plugin-react@^6.6.0

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/monod/npm-debug.log

npm install returned exit code 1

Action failed: npm install
```

I am going to retry the build. If it fails again, I'll have to revert this PR.

**Pull request merged**
