### PR TITLE
Improve print styles

### PR DESCRIPTION
**Pull request by jmaupetit**
- [x] Fix displayed URLs when printing document #140 
- [x] Fix list font size
- [x] Fix emojis size
- [x] Fix KaTeX equations 
- [x] Add print style support for various tags:
  - [x] `mark` #141
  - [x] `ins` #141

### CODE REVIEW

**Comment by willdurand** [comment]
Shouldn't we decreae emojione size for the preview panel too?

**Comment by jmaupetit** [comment]
@willdurand should we consider #141 as fixed?

**Comment by willdurand** [comment]
@jmaupetit yes!

**Comment by willdurand** [comment]
:+1:

**Pull request merged**
