### PR TITLE
Mobile view for small screens

### PR DESCRIPTION
**Pull request by willdurand**
## Purpose

I slightly changed the view for small screens. Now we get a reading view (that is usable). The editor is hidden, which is better since it is not really usable on mobile anyway.

## Screenshots

screen shot 2016-10-17 at 17 34 27

screen shot 2016-10-17 at 17 42 38

### CODE REVIEW

**Comment by willdurand** [comment]
Setting it as WIP again, because it does not work well with long sentences. It should wrap lines instead of having overflow.

**Comment by jmaupetit** [comment]
You mean long words right? If yes, I think those rules from [css-tricks](https://css-tricks.com/almanac/properties/w/word-break/) can help:

```css
-ms-word-break: break-all;
word-break: break-all;

// Non standard for webkit
word-break: break-word;

-webkit-hyphens: auto;
-moz-hyphens: auto;
hyphens: auto;
```

**Comment by willdurand** [comment]
A E2E test is failing but it is likely due to Saucelabs..

**Comment by willdurand** [comment]
So I slightly changed the footer and the global rendering. Looks good to me!

**Comment by jmaupetit** [comment]
🎉

**Pull request merged**
