### PR TITLE
[WIP] Add KaTeX basic support

### PR DESCRIPTION
**Pull request by willdurand**
Refs #119

### CODE REVIEW

**Comment by willdurand** [comment]
screen shot 2016-04-26 at 20 49 36

**Comment by willdurand** [comment]
So it works but if the content is definitely not responsive :(

**Comment by jmaupetit** [comment]
AFAIR as for LaTeX with long expressions. It's the writer responsibility to split its equation into multiple rows. And (print) font size can be optimized too.

**Comment by willdurand** [comment]
so let's merge this "as is"?

**Comment by willdurand** [comment]
I'm going to rebase this branch

**Comment by willdurand** [comment]
@jmaupetit I think we could merge this PR, and then use #142 to fix CSS for math formula.

**Comment by willdurand** [comment]
@jmaupetit I let you deal with this PR then

**Pull request merged**
