### PR TITLE
Proof read writing markdown file

### PR DESCRIPTION
**Pull request by codeahead14**
I have made changes to the Writing.md file as per review, comments and feedback. Opening a new PR as it would help for #hacktoberfest as well.

### CODE REVIEW

**Comment by codeahead14** [comment]
Hi @willdurand, any updates on this PR?

**Comment by willdurand** [comment]
mmh so this is a replacement for #228?

**Comment by codeahead14** [comment]
Hi @willdurand , yes it is. I have made all the necessary changes as per feedback and review.

**Comment by willdurand** [comment]
Awesome! Thanks @codeahead14 and happy hacktoberfest 🎃

**Pull request merged**
